/* eslint-disable @typescript-eslint/no-var-requires */

const { relative, join } = require('path');
const glob = require('glob');
const { promisify } = require('util');

const yargs = require('yargs');

const options = yargs
  .usage('Usage: generate-mapfile <src-folders>')
  .option('r', {
    alias: 'require',
    describe: 'Use require(...) calls instead of import(...)',
    type: 'boolean',
  })
  .option('e', {
    alias: 'extension',
    describe: 'keep full extension',
    type: 'boolean',
  })
  .option('g', {
    alias: 'glob',
    describe: 'glob to use for matching',
    type: 'string',
    default: '**/*.safetest.{j,t}s{,x}',
  })
  .demandCommand(1).argv;

const globAsync = promisify(glob);

(async () => {
  const importFn = options.require ? 'require' : 'import';
  let output = `// File generated by running: node node_modules/safetest/generate-mapfile ${process.argv
    .slice(2)
    .map((arg) => `'${arg}'`)
    .join(' ')}\n`;
  output += 'export const importMap = {\n';
  const existingKeys = new Set();
  for (const dir of options._) {
    for (const match of await globAsync(join(dir, options.glob))) {
      const key = relative(process.cwd(), match).replace(/\.[jt]sx?$/, '');
      if (!existingKeys.has(key)) {
        existingKeys.add(key);
        const importPath = './' + relative(dir, match);
        const value = options.extension
          ? importPath
          : importPath.replace(/\.[jt]sx?$/, '');
        output += `  '${key}': () => ${importFn}('${value}'),\n`;
      }
    }
  }
  output += '};';

  console.log(output);
})();
